### ISSUE TITLE
How to get filed value?

### ISSUE THREAD

**Issue by liaoxuewei** [udos86/flutter-fast-forms#15]
How to get or set filed value?

**Comment by diegonc** [comment]
I believe we must use `FastForm.of(context)?.values`. However, for some reason `FastForm.of(context)` is always returning `null`

**Comment by udos86** [comment]
- Values should always be read via `onChanged` listener on `FastForm` or `FastFormField`
- Values should only be set via `initialValue` constructor parameter

`FastForm.of` replicates `Form.of` and should not be used from the outside.

**Comment by udos86** [comment]
If you need to retrieve `FastFormState` via `FastForm.of()` you need to pass context either by using `Builder` or wrapping your form fields into a stand-alone widget (see https://youtu.be/xXNOkIuSYuA)
