### ISSUE TITLE
Missing implementation of [ChoiceChip.iconTheme] and [ChoiceChip.surfaceTintColor] on Flutter version 3.3.0

### ISSUE THREAD

**Issue by kuchienkz** [udos86/flutter-fast-forms#28]
After updating Flutter to latest version (v3.3.0 - 8/31/2022), my web project won't compile, because those missing implementations. I hope you can fix this asap, since you just have to literally add, like, 4 lines of code to fix this.

**Comment by udos86** [comment]
fixed in `8.0.0`
