### ISSUE TITLE
Error FastChoiceChip after update to Flutter 3.13.0

### ISSUE THREAD

**Issue by bennyprasetia** [udos86/flutter-fast-forms#38]
Hi Bro,
I got an error while run 'flutter run --verbose' 
iOS : 
`[ +103 ms] Failed to build iOS app
[   +1 ms] Error (Xcode): [+5023 ms] ../../../../../.pub-cache/hosted/pub.dev/flutter_fast_forms-11.1.0/lib/src/options/choice_chips.dart:6:7: Error: The non-abstract class 'FastChoiceChip' is missing implementations for these
members:`

Android :
`./../../../../.pub-cache/hosted/pub.dev/flutter_fast_forms-11.1.0/lib/src/options/choice_chips.dart:6:7: Error: The non-abstract class 'FastChoiceChip' is missing implementations for these members:
 - ChipAttributes.color
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class FastChoiceChip
      ^^^^^^^^^^^^^^
../../../flutter/tools/flutter/packages/flutter/lib/src/material/chip.dart:145:38: Context: 'ChipAttributes.color' is defined here.
  MaterialStateProperty<Color?>? get color;
                                     ^^^^^
Target kernel_snapshot failed: Exception`

Flutter version : 
Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (5 days ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0

Is there any suggestion ? 

Thanks

**Comment by udos86** [comment]
@bennyprasetia 

Please upgrade to latest version `12.0.0`.

This error was caused by a breaking change in Flutter `3.13.0`.
