### ISSUE TITLE
"minLines can't be greater than maxLines" - Simple be critical fix

### ISSUE THREAD

**Issue by pauldirectly** [udos86/flutter-fast-forms#50]
This problem make the FastTextField unusable in multiple lines context
----
in a FastTextField, if you specify 
minLines=2, maxLines=3

You will get assertion - "minLines can't be greater than maxLines".

the problem is simple mistake in assert logic in
src/meterial/text_form_field.dart: line 181

assert(
         (maxLines == null) || (minLines == null) || (maxLines >= minLines),
         "minLines can't be greater than maxLines",
       ),

should be:

assert(
         (maxLines == null) || (minLines == null) || (maxLines < minLines),
         "minLines can't be greater than maxLines",
       ),

**Comment by udos86** [comment]
@pauldirectly 

You're referencing code that is not part of this library but of the Flutter SDK itself.

Therefore it would be great if report this directly in the Flutter repository.

Thanks!
