### ISSUE TITLE
Flutter 3.24.0 cant build app with flutter-fast-form

### ISSUE THREAD

**Issue by jfest** [udos86/flutter-fast-forms#56]
Flutter 3.24.0-1.0.pre.487 • channel master • https://github.com/flutter/flutter.git
Framework • revision e0c051f47f (il y a 4 semaines) • 2024-08-07 01:52:41 -0400
Engine • revision 5a0fd5fbec
Tools • Dart 3.6.0 (build 3.6.0-122.0.dev) • DevTools 2.38.0

../../.pub-cache/hosted/pub.dev/flutter_fast_forms-17.1.0/lib/src/options/segmented_control.dart:100:12: Error: Type argument 'T' doesn't conform to the bound 'Object' of the type variable 'T' on 'CupertinoSlidingSegmentedControl'.
 - 'Object' is from 'dart:core'.
Try changing type arguments so that they conform to the bounds.
    child: CupertinoSlidingSegmentedControl<T>(

../flutter/packages/flutter/lib/src/cupertino/sliding_segmented_control.dart:304:40: Context: This is the type variable whose bound isn't conformed to.
class CupertinoSlidingSegmentedControl<T extends Object> extends StatefulWidget {
                                       ^
Failed to compile application.

**Comment by udos86** [comment]
@jfest 

Does this error also occur when you're switching to a stable `3.5.x` version of Dart?

**Comment by jfest** [comment]
@udos86 

Hello, switching to 3.5.2 it works. 

Thanks
